services:
  bot:
    build: .
    command: >
      sh -c "npx nodemon --legacy-watch --delay 1 --watch src src/index.bot.js"
    env_file: .env
    environment:
      NODE_ENV: development
      PORT: 10000
    volumes:
      - ./src:/app/src
      - bot-logs:/app/logs
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - bot-net

  dashboard:
    build: .
    command: >
      sh -c "npx nodemon --legacy-watch --delay 1 --watch src src/index.server.js"
    env_file: .env
    environment:
      NODE_ENV: development
      PORT: 10001
    ports:
      - "10001:10001"
    volumes:
      - ./src:/app/src
      - ./dashboard:/app/dashboard
      - bot-logs:/app/logs
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - bot-net

volumes:
  bot-logs:
  app-data:

networks:
  bot-net:
    driver: bridge